### ISSUE TITLE
 activate.sh, bootstrap.sh 파일 내의 변수 이슈

### ISSUE THREAD

**Issue by magis9790** [YOGYUI/HomeNetwork#10]
* Hillstate-Gwanggyosan/activate.sh
* Hillstate-Gwanggyosan/bootstrap.sh

 > 두개의 파일 내에 사용하고 있는 '$(realpath $0)' 의 변수가 새로 커밋되면서  '$(realpath $"0")' 으로 변경되면서 
   쉘 스크립트가 실행되지 않는 문제가 있는거 같습니다.
현재 저는 HAOS 를 시놀로지 NAS에 VMM을 사용하여 쓰고 있으나 새로 세팅하면서 쓸때는 잘 되었으나 이번에 새로 커밋된 내용중에 안되는 부분이 있어서 이렇게 이슈로 남겨 둡니다. 

** 좋은정보 공유해주셔서 너무 감사하고 잘쓰고 있습니다. ^^;

**Comment by YOGYUI** [comment]
여러 플랫폼용으로 테스트하던 걸 복구하지 않고 그대로 남겨놨네요 ^^;;
알려주셔서 감사합니다~
최대한 빠른 시일내에 수정해놓겠습니다

**Comment by YOGYUI** [comment]
@magis9790 스크립트 수정했으니 테스트 후 문제없으면 이슈 닫아주시기 바랍니다 ^^

**Comment by magis9790** [comment]
@YOGYUI 감사합니다 ^^;
